version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_quiz
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - quiz_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_quiz
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - quiz_network

networks:
  quiz_network:
    driver: bridge

volumes:
  mysql_data: